import { NextResponse } from "next/server";

const products = [
  {
    id: "f1c8fa42-6f35-49cf-9f6f-9d22a9fe6301",
    name: "Heirloom Tomatoes (1 lb)",
    farm: "Green Fork Farm",
    category: "vegetables",
    harvestDate: "2026-02-07T00:00:00-06:00",
    price: 4.5,
    status: "fresh",
    description:
      "Rich, colorful tomatoes grown in mineral soil and picked at peak ripeness for salads and roasting.",
    origin: "Green Fork Farm, Fredericksburg, TX",
    batchHarvest: "GF-2402",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Maya Rowan",
  },
  {
    id: "43e5e527-02d5-4c1c-b5f6-b54017e7b631",
    name: "Pasture Eggs (12)",
    farm: "Willow Ridge",
    category: "dairy",
    harvestDate: "2026-02-08T00:00:00-06:00",
    price: 6,
    status: "limited",
    description:
      "Pasture-raised eggs with deep yolks and clean flavor from a small mixed-flock operation.",
    origin: "Willow Ridge, Bastrop, TX",
    batchHarvest: "WR-208",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Eli Mercer",
  },
  {
    id: "ceeb689b-2635-439b-8140-c11bf07df7f9",
    name: "Strawberries (1 lb)",
    farm: "Sunvale Co-op",
    category: "fruits",
    harvestDate: "2026-02-06T00:00:00-06:00",
    price: 5.5,
    status: "out",
    description: "Early-season berries with bright sweetness and a soft finish.",
    origin: "Sunvale Co-op, Elgin, TX",
    batchHarvest: "SV-114",
    deliveryWindow: "Next week",
    farmerName: "Ana Solis",
  },
  {
    id: "4f8a6ff2-7c0b-4096-8dce-dff58c2f56ce",
    name: "Baby Kale (8 oz)",
    farm: "Cedar Lane",
    category: "vegetables",
    harvestDate: "2026-02-07T00:00:00-06:00",
    price: 3.25,
    status: "fresh",
    description:
      "Tender baby kale with a mild bite, cleaned and packed same day for quick weeknight meals.",
    origin: "Cedar Lane, Pflugerville, TX",
    batchHarvest: "CL-522",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Noah Pike",
  },
  {
    id: "4a723074-17f9-4fa2-b99d-63f56011f1fb",
    name: "Rainbow Carrots (1 lb)",
    farm: "Hollow Creek",
    category: "vegetables",
    harvestDate: "2026-02-07T00:00:00-06:00",
    price: 3.8,
    status: "fresh",
    description:
      "Sweet, crunchy heirloom carrot mix with natural color variation and strong earthy aroma.",
    origin: "Hollow Creek, Manor, TX",
    batchHarvest: "HC-309",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Leah Benton",
  },
  {
    id: "04ebc7f1-2d35-4d90-a1ac-61bdbf66bf8f",
    name: "Goat Cheese (6 oz)",
    farm: "Silver Meadow",
    category: "dairy",
    harvestDate: "2026-02-05T00:00:00-06:00",
    price: 7.75,
    status: "limited",
    description:
      "Small-batch chèvre with a creamy texture and subtle tang, made from pasture-fed milk.",
    origin: "Silver Meadow Creamery, Dripping Springs, TX",
    batchHarvest: "SM-2405",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Ruth Calder",
  },
  {
    id: "7b36bcdb-6d08-4c19-9944-79686ef17484",
    name: "Blueberries (6 oz)",
    farm: "Riverlight Farm",
    category: "fruits",
    harvestDate: "2026-02-08T00:00:00-06:00",
    price: 4.9,
    status: "fresh",
    description:
      "Firm, sweet berries harvested in cool morning hours to preserve texture and flavor.",
    origin: "Riverlight Farm, Lockhart, TX",
    batchHarvest: "RL-420",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Isaac Wynn",
  },
  {
    id: "5e163542-aeb9-4f1d-9d61-f0f03dddb3ee",
    name: "Sweet Corn (4 ears)",
    farm: "Prairie Bend",
    category: "vegetables",
    harvestDate: "2026-02-04T00:00:00-06:00",
    price: 4.2,
    status: "out",
    description: "Fresh sweet corn picked at sugar peak for grilling and summer salads.",
    origin: "Prairie Bend, Taylor, TX",
    batchHarvest: "PB-197",
    deliveryWindow: "Next week",
    farmerName: "Grace Holloway",
  },
  {
    id: "0a4c4f50-13e9-4b6a-95de-8e6dc89a0f07",
    name: "Russet Potatoes (2 lb)",
    farm: "Hollow Creek",
    category: "vegetables",
    harvestDate: "2026-02-09T00:00:00-06:00",
    price: 4.1,
    status: "fresh",
    description: "Starchy potatoes ideal for roasting, mash, and stews.",
    origin: "Hollow Creek, Manor, TX",
    batchHarvest: "HC-315",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Leah Benton",
  },
  {
    id: "8bc6f4ed-5f57-4d4f-91a8-f487a00bf4ab",
    name: "Yellow Onions (1.5 lb)",
    farm: "Green Fork Farm",
    category: "vegetables",
    harvestDate: "2026-02-09T00:00:00-06:00",
    price: 3.35,
    status: "fresh",
    description: "Aromatic onions with balanced sweetness for everyday cooking.",
    origin: "Green Fork Farm, Fredericksburg, TX",
    batchHarvest: "GF-2403",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Maya Rowan",
  },
  {
    id: "2f4fcf98-1f87-4a72-9e4f-31c66b72cd7b",
    name: "Zucchini (1 lb)",
    farm: "Cedar Lane",
    category: "vegetables",
    harvestDate: "2026-02-08T00:00:00-06:00",
    price: 3.6,
    status: "fresh",
    description: "Tender zucchini for sautés, grills, and quick pasta dishes.",
    origin: "Cedar Lane, Pflugerville, TX",
    batchHarvest: "CL-531",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Noah Pike",
  },
  {
    id: "f58c5a8d-cd29-4ed7-8204-9af718f6dad7",
    name: "Spinach (8 oz)",
    farm: "Prairie Bend",
    category: "vegetables",
    harvestDate: "2026-02-10T00:00:00-06:00",
    price: 3.9,
    status: "limited",
    description: "Washed baby spinach with a mild, fresh flavor.",
    origin: "Prairie Bend, Taylor, TX",
    batchHarvest: "PB-201",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Grace Holloway",
  },
  {
    id: "0ea29f88-2ff5-42f9-bc1f-d4d24bb89fe7",
    name: "Sweet Bell Peppers (1 lb)",
    farm: "Sunvale Co-op",
    category: "vegetables",
    harvestDate: "2026-02-06T00:00:00-06:00",
    price: 4.6,
    status: "limited",
    description: "Crisp red and yellow peppers with high natural sweetness.",
    origin: "Sunvale Co-op, Elgin, TX",
    batchHarvest: "SV-118",
    deliveryWindow: "Next week",
    farmerName: "Ana Solis",
  },
  {
    id: "eb8aab45-3dce-4552-aab9-24f10ac8bf8e",
    name: "Navel Oranges (2 lb)",
    farm: "Riverlight Farm",
    category: "fruits",
    harvestDate: "2026-02-08T00:00:00-06:00",
    price: 5.2,
    status: "fresh",
    description: "Juicy seedless oranges with bright citrus notes.",
    origin: "Riverlight Farm, Lockhart, TX",
    batchHarvest: "RL-423",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Isaac Wynn",
  },
  {
    id: "afb4d75c-8060-490f-aab0-50a04eb24c7e",
    name: "Honeycrisp Apples (2 lb)",
    farm: "Willow Ridge",
    category: "fruits",
    harvestDate: "2026-02-07T00:00:00-06:00",
    price: 6.8,
    status: "fresh",
    description: "Crunchy apples with a balanced sweet-tart profile.",
    origin: "Willow Ridge, Bastrop, TX",
    batchHarvest: "WR-211",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Eli Mercer",
  },
  {
    id: "f50dd172-c80e-4a95-8df3-7e4f4b829056",
    name: "Raspberries (6 oz)",
    farm: "Green Fork Farm",
    category: "fruits",
    harvestDate: "2026-02-10T00:00:00-06:00",
    price: 5.9,
    status: "limited",
    description: "Delicate berries with deep sweetness and perfume.",
    origin: "Green Fork Farm, Fredericksburg, TX",
    batchHarvest: "GF-2407",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Maya Rowan",
  },
  {
    id: "dd4a46f0-172d-426b-b6dd-e6e44d9555dc",
    name: "Whole Milk (1 qt)",
    farm: "Silver Meadow",
    category: "dairy",
    harvestDate: "2026-02-09T00:00:00-06:00",
    price: 4.7,
    status: "fresh",
    description: "Creamy whole milk from grass-fed herd, gently pasteurized.",
    origin: "Silver Meadow Creamery, Dripping Springs, TX",
    batchHarvest: "SM-2411",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Ruth Calder",
  },
  {
    id: "942f0805-19d8-4d91-8d92-edf2181f47eb",
    name: "Greek Yogurt (16 oz)",
    farm: "Willow Ridge",
    category: "dairy",
    harvestDate: "2026-02-07T00:00:00-06:00",
    price: 5.6,
    status: "limited",
    description: "Thick strained yogurt with clean tang and high protein.",
    origin: "Willow Ridge, Bastrop, TX",
    batchHarvest: "WR-214",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Eli Mercer",
  },
  {
    id: "335808fb-20e1-4695-aac9-39b7805da107",
    name: "Aged Cheddar (8 oz)",
    farm: "Silver Meadow",
    category: "dairy",
    harvestDate: "2026-02-04T00:00:00-06:00",
    price: 8.4,
    status: "out",
    description: "Sharp, nutty cheddar aged for depth and sliceability.",
    origin: "Silver Meadow Creamery, Dripping Springs, TX",
    batchHarvest: "SM-2398",
    deliveryWindow: "Next week",
    farmerName: "Ruth Calder",
  },
  {
    id: "bc2cf2d6-8138-4b79-9931-b5fbdad9df6e",
    name: "Ground Beef (1 lb)",
    farm: "Oak Valley Ranch",
    category: "meat",
    harvestDate: "2026-02-09T00:00:00-06:00",
    price: 9.25,
    status: "fresh",
    description: "80/20 ground beef from pasture-finished cattle.",
    origin: "Oak Valley Ranch, San Marcos, TX",
    batchHarvest: "OV-320",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "Hudson Reed",
  },
  {
    id: "8e0226a4-5eab-4c6e-9855-bf3f4f03cdaf",
    name: "Chicken Breasts (1.5 lb)",
    farm: "Pine Hollow Poultry",
    category: "meat",
    harvestDate: "2026-02-08T00:00:00-06:00",
    price: 11.5,
    status: "fresh",
    description: "Air-chilled chicken breasts from free-range birds.",
    origin: "Pine Hollow Poultry, Georgetown, TX",
    batchHarvest: "PH-188",
    deliveryWindow: "2-3 days in Austin metro",
    farmerName: "June Whitaker",
  },
];

export function GET() {
  return NextResponse.json(products);
}
